export const ADD_ENTRY = "ADD_ENTRY";
export const CHANGE_PLAYER_ONE = "CHANGE_PLAYER_ONE";
export const CHANGE_PLAYER_TWO = "CHANGE_PLAYER_TWO";
export const CHANGE_SCORE_ONE = "CHANGE_SCORE_ONE";
export const CHANGE_SCORE_TWO = "CHANGE_SCORE_TWO";